import type { Engine } from './engine.js'
import {
  RESET, CYAN, GREEN, YELLOW, GRAY, BOLD,
} from './constants.js'

export function showMenu(_engine: Engine): void {
  console.log(`${BOLD}${CYAN}╔ Menu principal${RESET}`)
  console.log(`${BOLD}${CYAN}║${RESET}`)
  console.log(`${BOLD}${CYAN}║  ${GRAY}── Configuration ──${RESET}`)
  console.log(`${BOLD}${CYAN}║  ${CYAN}1${RESET}.  Providers & clés API`)
  console.log(`${BOLD}${CYAN}║  ${CYAN}2${RESET}.  Mon profil`)
  console.log(`${BOLD}${CYAN}║${RESET}`)
  console.log(`${BOLD}${CYAN}║  ${GRAY}── Agents ──${RESET}`)
  console.log(`${BOLD}${CYAN}║  ${CYAN}3${RESET}.  Créer un agent`)
  console.log(`${BOLD}${CYAN}║  ${CYAN}4${RESET}.  Voir les agents`)
  console.log(`${BOLD}${CYAN}║  ${CYAN}5${RESET}.  Éditer un agent`)
  console.log(`${BOLD}${CYAN}║  ${CYAN}6${RESET}.  Skills & prompts`)
  console.log(`${BOLD}${CYAN}║${RESET}`)
  console.log(`${BOLD}${CYAN}║  ${GRAY}── Sessions ──${RESET}`)
  console.log(`${BOLD}${CYAN}║  ${CYAN}7${RESET}.  Démarrer une session`)
  console.log(`${BOLD}${CYAN}║  ${CYAN}8${RESET}.  Gérer les sessions`)
  console.log(`${BOLD}${CYAN}║${RESET}`)
  console.log(`${BOLD}${CYAN}║  ${GRAY}── Monitoring ──${RESET}`)
  console.log(`${BOLD}${CYAN}║  ${CYAN}9${RESET}.  Status & notifications`)
  console.log(`${BOLD}${CYAN}║${RESET}`)
  console.log(`${BOLD}${CYAN}║  ${GRAY}── Aide ──${RESET}`)
  console.log(`${BOLD}${CYAN}║  ${CYAN}10${RESET}. Commandes & aide`)
  console.log(`${BOLD}${CYAN}╚  ${CYAN}0${RESET}.  Quitter\n`)
  console.log(`${GRAY}Ou tapez /help, /create, /providers, un prompt, !cmd, @message...${RESET}`)
}

export function showHelp(engine: Engine): void {
  const agent = engine.agent
  console.log(`\n${BOLD}${CYAN}╔${RESET}`)
  console.log(`${BOLD}${CYAN}║  Minautor Agent Service — Commandes${RESET}`)
  console.log(`${BOLD}${CYAN}╚${RESET}`)
  console.log(`${GRAY}Agent: ${agent.displayName} (${agent.id})${RESET}`)
  console.log(`${GRAY}Model: ${agent.model}${RESET}`)
  console.log(`${GRAY}Tools: ${agent.toolNames.join(', ')}${RESET}\n`)
  console.log(`${BOLD}Menu :${RESET}`)
  console.log(`  ${GREEN}/menu${RESET}       Afficher le menu principal`)
  console.log(`  ${GREEN}/help${RESET}       Cette aide`)
  console.log(`  ${GREEN}/ ou /?${RESET}     Sélecteur de commandes complet`)
  console.log(`  ${GREEN}1-9${RESET}         Raccourcis du menu`)
  console.log(`  ${GREEN}0${RESET}           Quitter\n`)
  console.log(`${BOLD}Configuration :${RESET}`)
  console.log(`  ${GREEN}/profile${RESET}              Modifier ton profil (prénom, pseudo)`)
  console.log(`  ${GREEN}/providers${RESET}            Voir la liste des providers`)
  console.log(`  ${GREEN}/providers add${RESET}        Ajouter un fournisseur`)
  console.log(`  ${GREEN}/providers remove <nom>${RESET} Supprimer un fournisseur`)
  console.log(`  ${GREEN}/providers enable <nom>${RESET} Activer un fournisseur`)
  console.log(`  ${GREEN}/providers disable <nom>${RESET} Désactiver un fournisseur`)
  console.log(`  ${GREEN}/providers key <nom> <clé>${RESET} Définir/changer la clé API`)
  console.log(`  ${GREEN}/providers keys <nom>${RESET} Voir les clés API`)
  console.log(`  ${GREEN}/providers addkey <nom>${RESET} Ajouter une clé`)
  console.log(`  ${GREEN}/providers removekey <nom>${RESET} Supprimer une clé`)
  console.log(`  ${GREEN}/providers model <nom> <m>${RESET} Changer le modèle par défaut`)
  console.log(`  ${GREEN}/providers scan${RESET}        Scanner les providers locaux`)
  console.log(`  ${GREEN}/providers local${RESET}       Statut des providers locaux`)
  console.log(`\n${GRAY}── Rotation multi-clés ──${RESET}`)
  console.log(`  ${GREEN}1${RESET} → Provider > ${GREEN}Ajouter${RESET} une clé   Activer l'alternateur`)
  console.log(`  ${GRAY}   Bascule automatique sur une autre clé en cas de 429 (cooldown 60s)${RESET}`)
  console.log(`  ${GRAY}   Maximum 3 rotations par appel avant abandon${RESET}\n`)
  console.log(`${BOLD}Agents :${RESET}`)
  console.log(`  ${GREEN}/create${RESET}     Créer un agent (guidé avec certification PACO)`)
  console.log(`  ${GREEN}/edit${RESET}       Éditer un agent (nom, instructions, modèle)`)
  console.log(`  ${GREEN}/agents${RESET}     Lister tous les agents`)
  console.log(`  ${GREEN}/use <id>${RESET}   Charger un agent par son ID`)
  console.log(`  ${GREEN}/load <path>${RESET} Charger un agent depuis un fichier JSON\n`)
  console.log(`${BOLD}Sessions :${RESET}`)
  console.log(`  ${GREEN}/start${RESET}      Démarrer une session avec un agent`)
  console.log(`  ${GREEN}/session <id>${RESET} Changer de session`)
  console.log(`  ${GREEN}/sessions${RESET}   Lister les sessions`)
  console.log(`  ${GREEN}/new${RESET}       Nouvelle session`)
  console.log(`  ${GREEN}/info${RESET}      Infos de la session active\n`)
  console.log(`${BOLD}Monitoring :${RESET}`)
  console.log(`  ${GREEN}/status${RESET}              Status système (intercom, daemon, logbook)`)
  console.log(`  ${GREEN}/notifications${RESET}       Voir le filtre actif`)
  console.log(`  ${GREEN}/notifications filter <lvl>${RESET} Changer le niveau de filtre`)
  console.log(`  ${GREEN}/notifications history <j>${RESET} Historique des notifications`)
  console.log(`  ${GREEN}/logbook${RESET}              Voir les dernières entrées du logbook`)
  console.log(`  ${GREEN}/ps${RESET}                   Lister les agents en arrière-plan`)
  console.log(`  ${GREEN}/kill <nom>${RESET}           Tuer un agent en arrière-plan`)
  console.log(`  ${GREEN}/skills${RESET}               Lister les skills disponibles`)
  console.log(`  ${GREEN}/skills <nom>${RESET}          Afficher le contenu complet d'une skill\n`)
  console.log(`${BOLD}Prompt modes :${RESET}`)
  console.log(`  ${YELLOW}!commande${RESET}            Exécuter une commande shell`)
  console.log(`  ${YELLOW}@message${RESET}             Ajouter un message assistant`)
  console.log(`  ${YELLOW}!spawn <id> <instruction>${RESET} Lancer un agent en arrière-plan`)
  console.log(`  ${YELLOW}!spawn timer-man <interval>${RESET} Daemon timer longue durée`)
  console.log(`  ${YELLOW}texte${RESET}                Envoyer un prompt à l'agent LLM`)
  console.log(`  ${YELLOW}/exit${RESET}                Quitter\n`)
}
